use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn main() {
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();

    let proto_root = repo_root.join("protos");
    let out_dir = repo_root.join("src").join("gen");

    std::fs::create_dir_all(&out_dir).expect("failed to create src/gen/");

    let protos = &[
        "chalk/engine/v1/query_server.proto",
        "chalk/common/v1/online_query.proto",
        "chalk/common/v1/upload_features.proto",
        "chalk/common/v1/chalk_error.proto",
        "chalk/expression/v1/expression.proto",
        "chalk/graph/v1/graph.proto",
        "chalk/graph/v1/sources.proto",
        "chalk/graph/v2/sources.proto",
        "chalk/arrow/v1/arrow.proto",
        "chalk/dataframe/v1/dataframe.proto",
        "chalk/aggregate/v1/service.proto",
        "chalk/aggregate/v1/backfill.proto",
        "chalk/aggregate/v1/timeseries.proto",
        "chalk/auth/v1/permissions.proto",
        "chalk/auth/v1/audit.proto",
        "chalk/utils/v1/encoding.proto",
        "chalk/lsp/v1/lsp.proto",
    ];

    let proto_paths: Vec<PathBuf> = protos.iter().map(|p| proto_root.join(p)).collect();

    tonic_build::configure()
        .build_server(false)
        .out_dir(&out_dir)
        .compile_protos(&proto_paths, &[&proto_root])
        .expect("failed to compile protos");

    write_mod_rs(&out_dir);

    println!("Generated proto files in {}", out_dir.display());
}

/// A trie of proto module segments. Each generated file is named
/// `chalk.<pkg>.<version>.rs`; the dotted segments form the module path.
#[derive(Default)]
struct ModTree {
    children: BTreeMap<String, ModTree>,
}

/// Generates `mod.rs` from the `chalk.*.rs` files in `out_dir`, so a full
/// `rm -rf src/gen` + regenerate cycle leaves the module tree intact.
fn write_mod_rs(out_dir: &Path) {
    let mut root = ModTree::default();
    for entry in std::fs::read_dir(out_dir).expect("failed to read src/gen/") {
        let path = entry.expect("failed to read dir entry").path();
        let Some(stem) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let Some(stem) = stem.strip_suffix(".rs") else {
            continue;
        };
        if stem == "mod" {
            continue;
        }
        let mut node = &mut root;
        for segment in stem.split('.') {
            node = node.children.entry(segment.to_string()).or_default();
        }
    }

    let mut out = String::from(
        "// Code generated by tools/gen-protos. DO NOT EDIT.\n\
         //\n\
         // To regenerate, run ./generate.sh from the repo root.\n\n\
         #[allow(clippy::all, rustdoc::all)]\n",
    );
    for (name, child) in &root.children {
        write_mod(&mut out, name, child, &[], 0);
    }

    std::fs::write(out_dir.join("mod.rs"), out).expect("failed to write mod.rs");
}

fn write_mod(out: &mut String, name: &str, node: &ModTree, prefix: &[&str], depth: usize) {
    let indent = "    ".repeat(depth);
    out.push_str(&format!("{indent}pub mod {name} {{\n"));
    let mut path = prefix.to_vec();
    path.push(name);
    if node.children.is_empty() {
        // Leaf: include the generated file, e.g. "chalk.graph.v1.rs".
        out.push_str(&format!(
            "{indent}    include!(\"{}.rs\");\n",
            path.join(".")
        ));
    } else {
        for (child_name, child) in &node.children {
            write_mod(out, child_name, child, &path, depth + 1);
        }
    }
    out.push_str(&format!("{indent}}}\n"));
}
